### ISSUE TITLE
[Feature] esp32s2

### ISSUE THREAD

**Issue by diegonunesbr** [adafruit/Adafruit_TinyUSB_Arduino#102]
Any chances to work with esp32s2?

**Comment by hathach** [comment]
when this PR is merged, you could help testing out the PR and post your feedback there. https://github.com/espressif/arduino-esp32/pull/5333

**Comment by josjkasan** [comment]
Hello, any progress in this question? Any tutorial how to work with Arduino IDE?

**Comment by hathach** [comment]
Follow the above pr link to test it out. It is still under reviewed, you can give your feedback there
