### ISSUE TITLE
CR gets translated to a wrong keycode in hid.h

### ISSUE THREAD

**Issue by eugeneanikin** [adafruit/Adafruit_TinyUSB_Arduino#119]
### Operating System

MacOS

### IDE version

Arduino 1.8.15

### Board

all

### BSP version

github latest

### TinyUSB Library version

github latest

### Sketch

Adafruit Bluefruit nrf52 libraries/Periferal/hid_keyboard

### What happened ?

Compile the sketch for one of nrf52840 boards. Run it. Notice that newline never makes it accross.

### How to reproduce ?

see above.

**Comment by eugeneanikin** [comment]
The fix is in PR#118

**Comment by hathach** [comment]
merged and fixed by #118  thank you for your report.
