### ISSUE TITLE
hid_test.py should use get_feature_report() and not read()

### ISSUE THREAD

**Issue by jockm** [adafruit/Adafruit_TinyUSB_Arduino#137]
### Operating System

MacOS

### IDE version

Arduino 1.8.13

### Board

ESP32S2 Dev Module

### BSP version

2.0.1

### TinyUSB Library version

Release 1.6.0

### Sketch

examples/HID/hid_generic_inout

### What happened ?

if you run the `hid_test.py` script it will never return anything on the `dev.read(64)` command (line 20 of the script).  However if you change it to `dev.get_feature_report(0, 64)` it works correctly.  This makes sense because the code to send anything back to the host is in `set_report_callback()` and is therefore generating USB feature reports

### How to reproduce ?

1. Compile and upload hid_generic_inout.ino to Arduino device
2. run `python3 hid_test.py`
3. The app will hang after it sends data to the device

**Comment by hathach** [comment]
> if you run the hid_test.py script it will never return anything on the dev.read(64) command (line 20 of the script). However if you change it to dev.get_feature_report(0, 64) it works correctly. This makes sense because the code to send anything back to the host is in set_report_callback() and is therefore generating USB feature reports

the set report callback invoked when receiving report on both control and interrupt endpoints. This shouldn't be an issue. I tried, but cannot reproduce this issue on my Linux. This script has being tested on multiple ports and working just fine. I don't have an macOS to test with. It is probably issue with macos and/pr python hid package or something else. The suggestion to change to get feature report is not acccepted.
