### ISSUE TITLE
[Feature] How to send USB data to host without report id

### ISSUE THREAD

**Issue by Legion2** [adafruit/Adafruit_TinyUSB_Arduino#153]
**Is your feature request related to a problem? Please describe.**
I want to send raw USB HID data to the host, without an report id.
On Avr platform I use the arduino usb core, which allows to call `USB_Send` directly without the `SendReport` wrapper:

https://github.com/arduino/ArduinoCore-avr/blob/2cebe625833afcdb76cc941ccf90e5f5fefc27a9/libraries/HID/src/HID.cpp#L89-L96

**Describe the solution you'd like**
Allow to send raw USB HID data and omit the report id, maybe add an extra function for raw data.

**Describe alternatives you've considered**
Using an alternative HID library.

**Additional context**
I try to replicate the behavior which is already implemented for avr for samd platform.

**Comment by hathach** [comment]
This is not feature, please don’t open question in github issue and use the forum for it as suggested by the issue template
