### ISSUE TITLE
Definition of HID_REPORT_ID_N missing the 2nd parameter

### ISSUE THREAD

**Issue by ReeceWeb** [adafruit/Adafruit_TinyUSB_Arduino#158]
### Operating System

Others

### IDE version

Any

### Board

Any (not hardware specific)

### BSP version

n/a

### TinyUSB Library version

GitHub latest

### Sketch

n/a

### What happened ?

This line in src/class/hid/hid.h is incorrect:
#define HID_REPORT_ID_N(x) HID_REPORT_ITEM(x, RI_GLOBAL_REPORT_ID, RI_TYPE_GLOBAL, n),

It should read:
#define HID_REPORT_ID_N(x, n) HID_REPORT_ITEM(x, RI_GLOBAL_REPORT_ID, RI_TYPE_GLOBAL, n),

Note:  This appears to be present in the original tinyusb project, but I'm filing here too since it isn't clear how frequently this library re-syncs with tinyusb:  https://github.com/hathach/tinyusb/issues/1329#issue-1140464002

### How to reproduce ?

Source Inspection

**Comment by hathach** [comment]
fixed in tinyusb upstream, will be fixed in the next release
