### ISSUE TITLE
Consider to add ESP32-S3 support？[Feature]

### ISSUE THREAD

**Issue by mastwet** [adafruit/Adafruit_TinyUSB_Arduino#165]
When I Use my ESP32-S3 to run a demo of this project,a MIDI demo.I found that my computer cannot identify the device.Is that it cant support ESP32-S3?Or Probelum is mine.
If it cant support ESP32-S3 yet,I wish it can support it.
If it is my probelum,i will check it out.
Thank you very much.

**Comment by hathach** [comment]
it should be supported, if it does not work, please open an bug report with detailed info to reproduce
