### ISSUE TITLE
[Feature]Add PICO PIO USB support

### ISSUE THREAD

**Issue by sfranzyshen** [adafruit/Adafruit_TinyUSB_Arduino#169]
Add support for https://github.com/sekigon-gonnoc/Pico-PIO-USB

with the latest pull request to Pico-PIO-USB ... TinyUSB support has been added
https://github.com/sekigon-gonnoc/Pico-PIO-USB/pull/22 

and there is a active pull request to TinyUSB  itself ...
https://github.com/hathach/tinyusb/pull/1412

Ref.
https://github.com/earlephilhower/arduino-pico/issues/582
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/168

**Comment by hathach** [comment]
we will add host support to this library, but there is always some lag between this arduino library and tinyusb upstream. Please be patient

**Comment by kilograham** [comment]
please hold off on this; i would like to back-out and fix up the way the PIO support is integrated into the build. It will likely break whatever you do here.

**Comment by kilograham** [comment]
I added a PR https://github.com/hathach/tinyusb/pull/1467

**Comment by sfranzyshen** [comment]
looks like pull-request #173 and release 1.11.0 - Updated tinyusb to support rp2040 pio usb host handled this?

**Comment by hathach** [comment]
no, it is an weekly scheduled release probably by script on all adafruit repo. and only update tinyusb core only.

**Comment by JonnyHaystack** [comment]
Just curious, is there something that makes implementing the host API easier with PIO USB than with normal USB?

**Comment by tannewt** [comment]
> Just curious, is there something that makes implementing the host API easier with PIO USB than with normal USB?

I don't think so. The appeal of using PIO is having the USB device active at the same time.

**Comment by JonnyHaystack** [comment]
> > Just curious, is there something that makes implementing the host API easier with PIO USB than with normal USB?
> 
> I don't think so. The appeal of using PIO is having the USB device active at the same time.

Hmm okay, well I hope it's planned to have host support with the built-in USB controller as well 🙏
I've been hoping to move to this library for an existing device I designed, which uses the actual USB controller for USB host, and I use the PIO for other comms so wouldn't be able to use PIO USB anyway.
