### ISSUE TITLE
webusb example - RGB LED

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_TinyUSB_Arduino#21]
please have an example for 3 x PWM output - so we can use https://webusb.github.io/arduino/demos/rgb/

**Comment by PTS93** [comment]
Kind of related, where is the arduino sketch for the existing webusb example?

**Comment by hathach** [comment]
@PTS93 after these 2 PRs 
https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/313
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/22

starting with nrf first, I will update the samd core later on.

**Comment by hathach** [comment]
> please have an example for 3 x PWM output - so we can use https://webusb.github.io/arduino/demos/rgb/

I think it is better to use on-board neopixel which is on most of our feather board. 3 PWM work as well, but it is secondary via compiler switch.

**Comment by ladyada** [comment]
OK yes neopixel is good!

**Comment by hathach** [comment]
@PTS93 it is merged to https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples/WebUSB/webusb_serial

**Comment by PTS93** [comment]
Awesome! I wanted to make a more elaborate example with the Circuit Playground Express unless there are already plans for something like that?

**Comment by hathach** [comment]
@PTS93 feel free to do so, I push an PR for webusb-rgb to control on-board neopixel already, you may  want to check that out. My javascript and html already exceed its limit with these 2 examples :D
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/23

**Comment by PTS93** [comment]
That's helpful, thank you!
My web frontend skills are a bit rusty but I should be able to make something nice.
Do I understand correctly that with webusb you just send buffers back and forth like with raw hid?
That serial.js doesn't look like its doing anything that would be specific to classical UART.

**Comment by hathach** [comment]
@PTS93 webUSB specs actually doesn't say that, it is more like an optional extension. However, this Arduino library did implement the webusb as vendor class driver, and indeed as an subclass of Stream much like Serial for user convenience.
