### ISSUE TITLE
Support for UAC device under Arduino

### ISSUE THREAD

**Issue by lu7did** [adafruit/Adafruit_TinyUSB_Arduino#212]
**Is your feature request related to a problem? Please describe.**
Unable to spot an example/template of a UAC device showing how to implement an sound card under Arduino IDE (rp2040)

**Describe the solution you'd like**
A sample code that can be used as a template.

**Describe alternatives you've considered**
Instructions or guidelines on how to use existing examples such as uac2_headset to work under the Arduino IDE (rp2040)

**Additional context**
quite difficult to make it work because of missing dependencies.

Thanks in advance

**Comment by hathach** [comment]
won't implemented since UAC is still WIP in tinyusb core. You should start your own c (pico-sddk) project since UAC is a bit complicated to port to audio.
