### ISSUE TITLE
Release specific key in keyboard's HID report

### ISSUE THREAD

**Issue by vishesh-varma** [adafruit/Adafruit_TinyUSB_Arduino#216]
Currently, there are 3 functions in `Adafruit_USBD_HID.h` file, which are:
- `keyboardReport(uint8_t report_id, uint8_t modifier, uint8_t keycode[6]);`
     Presses up to 6 keys + a modifier.
- `keyboardPress(uint8_t report_id, char ch);`
     Presses the specified character.
- `keyboardRelease(uint8_t report_id);`
     Releases all the keys currently pressed.

Since there is a function that presses one specific key, it makes sense to have a function that would only release the specified key, and not all of them.
The use case here is pretty apparent, when switching between different combinations of keys, one can only press the next combination after releasing the currently pressed one.

**Comment by hathach** [comment]
it does not make sense to me, the press() is mostly helper only. Application should manage its own key state with keyboardReport()
