### ISSUE TITLE
multiple definition of dcd_esp32sx.c

### ISSUE THREAD

**Issue by tomaszduda23** [adafruit/Adafruit_TinyUSB_Arduino#227]
### Operating System

Linux

### IDE version

5.2.0

### Board

lolin_s2_mini

### ArduinoCore version

2.0.5

### TinyUSB Library version

1.14.4

### Sketch (attached txt file)

A few functions is declared in 2 places e.g. dcd_init. Is there any way to link it without error?

### What happened ?

/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_remote_wakeup':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:213: multiple definition of `dcd_remote_wakeup'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:257: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_edpt_open':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:256: multiple definition of `dcd_edpt_open'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:292: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_edpt_close_all':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:326: multiple definition of `dcd_edpt_close_all'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:370: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_edpt_xfer':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:350: multiple definition of `dcd_edpt_xfer'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:394: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_set_address':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:204: multiple definition of `dcd_set_address'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:248: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_edpt_stall':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:402: multiple definition of `dcd_edpt_stall'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:446: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_edpt_clear_stall':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:456: multiple definition of `dcd_edpt_clear_stall'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:500: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_int_enable':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:849: multiple definition of `dcd_int_enable'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:911: first defined here
/home/bh/.platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-white-control/lib78c/libAdafruit TinyUSB Library.a(dcd_esp32sx.c.o): in function `dcd_int_disable':
/home/bh/git/github/esphome/esphome/.esphome/build/esp-white-control/.piolibdeps/esp-white-control/Adafruit TinyUSB Library/src/portable/espressif/esp32sx/dcd_esp32sx.c:855: multiple definition of `dcd_int_disable'; /home/bh/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s2/lib/libarduino_tinyusb.a(dcd_esp32sx.c.obj):/Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/arduino_tinyusb/src/dcd_esp32sx.c:917: first defined here

### How to reproduce ?

n/a

**Comment by hathach** [comment]
this should be no problem when using with Arduino IDE. For other IDE, may you try to remove this file to see if that work 
- https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/src/portable/espressif/esp32sx
