### ISSUE TITLE
[Pico 2040] Compilation errors with PICO_SHARED_IRQ_HANDLER_LOWEST_ORDER_PRIORITY

### ISSUE THREAD

**Issue by noisysoil** [adafruit/Adafruit_TinyUSB_Arduino#261]
### Operating System

Linux

### Arduino IDE version

2.0.4

### Board

Pico 2040

### ArduinoCore version

Arduino Mbed for Pico 2040 version 4.0.2

### TinyUSB Library version

2.0.0

### Sketch as ATTACHED TXT

From the Adafruit TinyUSB library examples:
hid_gamepad.ino

(Or any other)

### Compiled Log as ATTACHED TXT

.../Arduino/libraries/Adafruit_TinyUSB_Library/src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp:108:26: error: 'PICO_SHARED_IRQ_HANDLER_LOWEST_ORDER_PRIORITY' was not declared in this scope
                          PICO_SHARED_IRQ_HANDLER_LOWEST_ORDER_PRIORITY);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### What happened ?

Compilation failure.

### How to reproduce ?

Compile any USB example from the 2.0.0 Adafruit library version.

**Comment by hathach** [comment]
do you know which pico-sdk version that mbed core is based on ?
