### ISSUE TITLE
Multiple definition of symbols with ESP32 2.0.8 

### ISSUE THREAD

**Issue by tomrodeheffer** [adafruit/Adafruit_TinyUSB_Arduino#284]
### Operating System

Linux

### Arduino IDE version

Arduino IDE 2.1.0

### Board

UM Feather S3

### ArduinoCore version

esp32 2.0.8

### TinyUSB Library version

Adafruit TinyUSB Library 2.0.3

### Sketch as ATTACHED TXT

```
#include <Adafruit_TinyUSB.h>
void setup() { }
void loop() { }
```

### Compiled Log as ATTACHED TXT

[TinyUSBLog.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/11288508/TinyUSBLog.txt)

### What happened ?

Compilation fails due to various symbols (tud_vendor_n_mounted, tud_vendor_n_available, etc) being multiply defined. This started to happen with ESP32 2.0.8 which was released on April 20, 2023 (today). Note that the sketch is about the smallest possible sketch that could illustrate this problem.

### How to reproduce ?

Attempt to compile the sketch with Adafruit TinyUSB 2.0.3 and ESP32 2.0.8

**Comment by hathach** [comment]
thanks, this can probably be fixed by sync up this library with tinyusb core that matches one used by esp32. We will fix this soon enough.
