### ISSUE TITLE
ESP32 DevkitC Compatibility

### ISSUE THREAD

**Issue by domwolfy** [adafruit/Adafruit_TinyUSB_Arduino#304]
### Operating System

Linux

### Arduino IDE version

2.1.0

### Board

ESP32 DevkitC

### ArduinoCore version

N/A I think?

### TinyUSB Library version

Githublatest

### Sketch as ATTACHED TXT

[sketch.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/11437765/sketch.txt)

### Compiled Log as ATTACHED TXT

[Compiled log.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/11437766/Compiled.log.txt)

### What happened ?

On compiling error: 'Adafruit_USBD_MIDI' does not name a type; did you mean 'Adafruit_USBD_CDC'?

### How to reproduce ?

Just compile with above parameters

### Screenshots

I'd like to know if this board is actually incompatibile with this library?
I know the board doesn't have USB native, I thought this library with TinyUSB was to overcome that problem?
The readme lists esp32s in compatible boards, if this board is an exception, what makes it unsupportable?
some esp32 boards will work but not others should the readme not clarify this?

**Comment by hathach** [comment]
question should be in discussion
