### ISSUE TITLE
keyboard LEDs code example?

### ISSUE THREAD

**Issue by WormPatch** [adafruit/Adafruit_TinyUSB_Arduino#325]
can someone pull a simple program to read/write keyboard LEDs (capslock, mayus, .etc) bitfield in /examples?

would help a lot thanks ^-^

**Comment by hathach** [comment]
please use discussion instead

**Comment by WormPatch** [comment]
> please use discussion instead

how, im not used to github

**Comment by WormPatch** [comment]
> please use discussion instead

ok:
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/discussions/326
