### ISSUE TITLE
[Bug] bcdUSB value

### ISSUE THREAD

**Issue by kaysievers** [adafruit/Adafruit_TinyUSB_Arduino#36]
The call:
  USBDevice.setVersion(0x2010);

was intended to be:
  USBDevice.setVersion(0x0201);
?

https://github.com/adafruit/Adafruit_TinyUSB_Arduino/blob/4c62e5ceefbd031acf467795f9c42b54548e1f62/src/Adafruit_USBD_WebUSB.cpp#L130

**Comment by hathach** [comment]
Yeah, it is a stupid bug, no idea how it could work so well so far :D
