### ISSUE TITLE
Errors when compiling the TinyUSB lbrary using version 2.3.3

### ISSUE THREAD

**Issue by DonWT** [adafruit/Adafruit_TinyUSB_Arduino#365]
### Operating System

Windows 10

### Arduino IDE version

Arduino 2.2.1

### Board

Arduino Nano ESP32

### ArduinoCore version

Arduino Nano ESP32
![image](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/135274154/b3572f70-621b-4c34-847d-2126ce57041b)

### TinyUSB Library version

2.3.3

### Sketch as ATTACHED TXT

![image](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/135274154/f2759748-419c-40f7-ab2f-2ab17ba17a65)

[Simple_USB_MIDI_test.ino.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/14031512/Simple_USB_MIDI_test.ino.txt)

### Compiled Log as ATTACHED TXT

c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:107:49: error: 'CFG_TUH_CDC_FTDI_VID_PID_LIST' undeclared here (not in a function); did you mean 'CFG_TUH_CDC_FTDI'?
 static uint16_t const ftdi_vid_pid_list[][2] = {CFG_TUH_CDC_FTDI_VID_PID_LIST};
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 CFG_TUH_CDC_FTDI
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:122:51: error: 'CFG_TUH_CDC_CP210X_VID_PID_LIST' undeclared here (not in a function); did you mean 'CFG_TUH_CDC_CP210X'?
 static uint16_t const cp210x_vid_pid_list[][2] = {CFG_TUH_CDC_CP210X_VID_PID_LIST};
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   CFG_TUH_CDC_CP210X
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:122:51: error: initializer element is not constant
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:122:51: note: (near initialization for 'cp210x_vid_pid_list[0][0]')
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:137:50: error: 'CFG_TUH_CDC_CH34X_VID_PID_LIST' undeclared here (not in a function); did you mean 'CFG_TUH_CDC_CH34X'?
 static uint16_t const ch34x_vid_pid_list[][2] = {CFG_TUH_CDC_CH34X_VID_PID_LIST};
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  CFG_TUH_CDC_CH34X
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:137:50: error: initializer element is not constant
c:\Users\Don\Arduino\libraries\Adafruit_TinyUSB_Library\src\class\cdc\cdc_host.c:137:50: note: (near initialization for 'ch34x_vid_pid_list[0][0]')

### What happened ?

The sketch compiles clean and runs against the 2.3.2 version of the Adafruit TinyUSB Library but the updated Adafruit library in version 2.3.3 fails with the above error messages.

Reverting back to 2.3.2 and everything is working again.

### How to reproduce ?

Attempt to compile the above sketch against the 2.3.3 version of the library and see the compiler error messages.

**Comment by Shonky-Donkey** [comment]
I spent about 3 hours today trying to figure out this same issue. I get the same thing with the "midi_test" example code supplied with the TinyUSB library.

**Comment by hathach** [comment]
should be fixed by #367, current ci is setup to build with esp32 v3 (alpha), and didn't catch these out of sync error.
