### ISSUE TITLE
compile errors if option "USB Firmware MSC On Boot:" is "Enabled"

### ISSUE THREAD

**Issue by beta-tester** [adafruit/Adafruit_TinyUSB_Arduino#395]
### Operating System

Linux

### Arduino IDE version

2.3.2

### Board

ESP32-S3 Dev Module

### ArduinoCore version

esp 2.0.11

### TinyUSB Library version

3.1.0

### Sketch as ATTACHED TXT

[hid_dual_interfaces.ino](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/blob/master/examples/HID/hid_dual_interfaces/hid_dual_interfaces.ino)

### Compiled Log as ATTACHED TXT

[compile error.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/14361955/compile.error.txt)

### What happened ?

if option "USB Firmware MSC On Boot:" is "Enabled", compiling the sketch will fail.

### How to reproduce ?

1. open example sketch "hid_dual_interfaces.ino"
2.  select Board: "ESP32-S3 Dev Module", USB Firmware MSC On Boot: "Enabled", USB Mode: "USB-OTG"
3. compile/verify
4. => compiler error

### Screenshots

![image](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/4750719/79c920e3-3498-4998-9778-d538892a1b22)

**Comment by hathach** [comment]
only set CDC on boot, other MSC/DFU on boot is not supported.

**Comment by beta-tester** [comment]
is it possible to bring up a warning with a message that tells that these combination of settings are wrong, instead of just compiler errors from codes that tells a newbie nothing?
