### ISSUE TITLE
RNDIS/USB network example

### ISSUE THREAD

**Issue by i-am-shodan** [adafruit/Adafruit_TinyUSB_Arduino#403]
**Is your feature request related to a problem? Please describe.**
The TinyUSB project has an example of USB networking in the examples dir but this isn't available as a class here

**Describe the solution you'd like**
An example of creating a RNDIS device with this library

**Describe alternatives you've considered**
I've tried to create a class from the MIDI implementation but I can't get it working as the interface doesn't appear. This is on an ESP32-S3 which it should work on. 

**Additional context**
No

**Comment by hathach** [comment]
we have no plan to add C++ class for rndis, you can use the native tinyusb API. PRs are welcome.

**Comment by i-am-shodan** [comment]
Do you have a link to your plan?

**Comment by hathach** [comment]
issue & pr list is the plan.
