### ISSUE TITLE
cant verify correctly error: missing Adafruit_USBD_CDC.h file eventhough i have it.

### ISSUE THREAD

**Issue by fabiendostie** [adafruit/Adafruit_TinyUSB_Arduino#410]
### Operating System

MacOS

### Arduino IDE version

2.3.2

### Board

Seeduino Xiao samd21

### ArduinoCore version

1.8.5

### TinyUSB Library version

Adafruit TinyUSB 3.1.1

### Sketch as ATTACHED TXT

[https://github.com/fabiendostie/Adafruit_TinyUSB_Issue/blob/main/Xiao_samd21_midi_HC-sr04.ino](url)

### Compiled Log as ATTACHED TXT

```
In file included from /private/var/folders/k0/hjpsy66n3hg335tq13ylq_jc0000gn/T/arduino/sketches/4F23009D6D78F625C1DD46B58E7A6D24/sketch/ultrasonicMIDI_v2.ino.cpp:1:0:
/Users/lefab/Library/Arduino15/packages/Seeeduino/hardware/samd/1.8.5/cores/arduino/Arduino.h:173:10: fatal error: Adafruit_USBD_CDC.h: No such file or directory
 #include "Adafruit_USBD_CDC.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
```

### What happened ?

I cant seem to be able to compile my project because of a missing Adafruit_USBD_CDC.h file. The thing is that, the file in question is on my system: /Users/lefab/Documents/Arduino/libraries/Adafruit_TinyUSB_Library/src/arduino/Adafruit_USBD_CDC.h
So I'm a little puzzled.

### How to reproduce ?

Just load the info file and try to verify the sketch.

### Debug Log

I do not know how to produce this

### Screenshots

<img width="667" alt="Screenshot 2024-03-22 at 23 28 04" src="https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/53846121/86191cbf-2f6f-4b53-9717-02b86b531dfd">
<img width="1363" alt="Screenshot 2024-03-22 at 23 31 26" src="https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/53846121/3afa3aec-bdf0-4680-9ec8-d7af783d097a">
<img width="276" alt="Screenshot 2024-03-22 at 23 33 36" src="https://github.com/adafruit/Adafruit_TinyUSB_Arduino/assets/53846121/203a09f7-ebb0-4dbe-b752-4349195591d7">

**Comment by hathach** [comment]
Board is not supported, check with board maker for support

**Comment by fabiendostie** [comment]
The Xiao samd21? I've seen it in the list, and actually had it working for
a different project using this library.

--
. | Fabien Dostie |
.///Coloriste Resolve | Montage Online VR-HD
.//Compositing | VR Stitching + editing
./DIT | DMT | V/A AQTIS 514 IATSE 667
.Tech. Scène IATSE 56
C: 438.357.3462 W: fabiendostie.com
