### ISSUE TITLE
[Bug] 0 documentation in this project

### ISSUE THREAD

**Issue by akamensky** [adafruit/Adafruit_TinyUSB_Arduino#44]
**Describe the bug**
Uh oh, this project has 0 documentation (examples are not documentation)

**Set up (please complete the following information)**
 - N/A
 - TinyUSB library version 0.8.1
 - N/A
 - N/A

**To Reproduce**
1. Attempt to write anything that is not covered by examples
2. ...

**Expected behavior**
A clear documentation (even one liners in-code) is available

**Additional context**
I don't think how can anyone use this library w/o documentation. Not even code comments (other than license).

**Comment by hathach** [comment]
I currently don't have time to write documentation yet. If you are not pleased with the lib, just use another one.
