### ISSUE TITLE
ESP32 C6 Tools -> USB Stack menu not showing

### ISSUE THREAD

**Issue by ghostintranslation** [adafruit/Adafruit_TinyUSB_Arduino#480]
### Operating System

MacOS

### Arduino IDE version

Arduino 2.3.4

### Board

ESP32-C6-DevKitM-1

### ArduinoCore version

esp32 3.0.7

### TinyUSB Library version

3.5.2

### Sketch as ATTACHED TXT

examples/Adafruit TinyUSB Library/MIDI/midi_test.ino

### Compiled Log as ATTACHED TXT

exit status 1

Compilation error: 'Adafruit_USBD_MIDI' does not name a type; did you mean 'Adafruit_USBH_CDC'?

### What happened ?

I can't compile the sketch.

This seems to be that I can't see the Tools->USB Stack menu when selecting any ESP32 board. I do see that menu and can select it and then build for a Raspberry Pico. So it looks like it is only a problem with the ESP32 core?

### How to reproduce ?

Select a ESP32 board, I tried many and it's the same for all.
Go to Tools, there won't be a USB Stack menu.

**Comment by hathach** [comment]
esp32 does not have menu (will update readme later), also C6 does not have OTG and not supported.
