### ISSUE TITLE
CDC no_serial example is broken

### ISSUE THREAD

**Issue by JeffCalwood** [adafruit/Adafruit_TinyUSB_Arduino#481]
### Operating System

Windows 10

### Arduino IDE version

Arduino 2.3.4

### Board

XIAO SAMD21

### ArduinoCore version

?

### TinyUSB Library version

3.4.2

### Sketch as ATTACHED TXT

happened to notice that the CDC no_serial example does not actually toggle the BUILTIN_LED as intended (no code to invert the static state variable). otherwise functional though.
also: in this example, there is absolutely no USB configuration left, so the subsequent 
```
  if (TinyUSBDevice.mounted()) {
    TinyUSBDevice.detach();
    delay(10);
    TinyUSBDevice.attach();
  }
```
will never happen here (tested). Although in all other scenarios there may be merit in this test, in this particular case maybe a comment would be educational.

**Comment by hathach** [comment]
XIAO SAMD with latest lib is not supported, either tell xiao to update their core or use the old version of this library
