### ISSUE TITLE
Cannot compile   usb_hid.mouseButtonRelease(0);

### ISSUE THREAD

**Issue by cyborg5** [adafruit/Adafruit_TinyUSB_Arduino#52]
**Describe the bug**
Adding a statement such as "usb_hid.mouseButtonRelease(0);" causes a compiler error.

C:\Users\Chris.cy\Documents\Arduino\Freedom Wing\my_hid_mouse/my_hid_mouse.ino:72: undefined reference to `Adafruit_USBD_HID::mouseButtonRelease(unsigned char)'

I see in the definition the method is defined as

  static inline bool mouseButtonRelease(uint8_t report_id);

Is there some special syntax when invoking a static inline method?

**Comment by hathach** [comment]
ah sorry, there is typo in prototype for that function PR fix is on the way #53 , will merge when ci passes. Thank you for reporting the issue.

**Comment by hathach** [comment]
it should be fixed with the current master. Please check to see if that works for you.
