### ISSUE TITLE
Doxygen link 404's

### ISSUE THREAD

**Issue by dherrada** [adafruit/Adafruit_TinyUSB_Arduino#61]

**Comment by siddacious** [comment]
"fixed". It's not 404ing anymore but there's no docs being built.

**Comment by PTS93** [comment]
wait there is a doxygen setup already? I didn't see anything so far for any of the TinyUSB related repos. Was thinking about setting that up myself.

**Comment by siddacious** [comment]
There is not. Any help would be welcome :)

You can check out most of the other Arduino repos for an example of how we like to set them up.
