### ISSUE TITLE
Library dependencies

### ISSUE THREAD

**Issue by nanosonde** [adafruit/Adafruit_TinyUSB_Arduino#62]
Hi!

Is it really necessary to have all those library dependencies listed in the file library.properties?
```
depends=Adafruit SPIFlash, MIDI Library, Adafruit seesaw Library, Adafruit NeoPixel, SdFat - Adafruit Fork, SD, Adafruit Circuit Playground
```
For example PlatformIO tries to pull in all those dependencies although they are not really required for the sketch to compile as it only uses the Adafruit TinyUSB library.

**Comment by PTS93** [comment]
not really an option around this as they are needed for the examples, there would need to be an optional dependency field which is not supported atm by Arduino

**Comment by ladyada** [comment]
yes - they are required to test the examples. 
there's a way around platformio's dependancy management, @ivankravets can help you! :)

**Comment by nanosonde** [comment]
Ok, then I will have to turn off the LDF automatic mode.
