### ISSUE TITLE
[Feature] ESP-32 Support

### ISSUE THREAD

**Issue by conde2** [adafruit/Adafruit_TinyUSB_Arduino#68]
**Is your feature request related to a problem? Please describe.**

Is there any way this project support ESP32 boards (feather huzzah32), or is this already a thing? 

I know that TinyUSB does already support ESP32, not sure if this library does.

**Comment by hathach** [comment]
only esp32s2 has usb support, even with that It will largely depends on the esp arduino core decide what to do what tinyusb port in the core, maybe they want an optimized version on their own.
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/63#issuecomment-627746905
