### ISSUE TITLE
WebUSB demo html page 404

### ISSUE THREAD

**Issue by jpliew** [adafruit/Adafruit_TinyUSB_Arduino#70]
Link referred from https://learn.adafruit.com/using-webusb-with-arduino-and-tinyusb/serial-communications-example

going to https://adafruit.github.io/Adafruit_TinyUSB_Arduino/examples/webusb-serial

producing a 404

**Comment by hathach** [comment]
thank for reporting the issue, this is fixed. Somehow the repo pages setting is changed from `master/root` to `gh-pages` (which isn't hosting the example).

**Comment by jpliew** [comment]
still 404

**Comment by hathach** [comment]
please add trailing `/` to the url,  github page probably change how they handle url, ` https://adafruit.github.io/Adafruit_TinyUSB_Arduino/examples/webusb-serial/` , or better have explicitly add index.html to the url as well. I have updated the example with index.html and will update the learn guide as well.
