### ISSUE TITLE
MIDI Echo

### ISSUE THREAD

**Issue by Kprellz** [adafruit/Adafruit_TinyUSB_Arduino#74]
Hey ya'll, 
Seem to be experiencing an issue where any incoming Midi message gets echo'd back to the sender. Is there a way to prevent this? or is this a bug of some kind?
ItsyBitsy M0
mac osx 10.15.5
even the example program does this. 

attached is a screen shot of MIDI Monitor reading midi messages to and from the device. I wrote a simple code to just send out a note on ever second or so.  the only code in my Loop is MIDI.read();

![Screen Shot 2021-03-25 at 11 46 07 PM](https://user-images.githubusercontent.com/68045029/112574266-52f7a580-8dc4-11eb-9361-3990f08bd498.png)

**Comment by Kprellz** [comment]
Also tested on a Metro M0 Express to the same results.

**Comment by Kprellz** [comment]
Figured this one out actually. anyone having a similar issue can simply due MIDI.turnThruOff();

**Comment by dkadrios** [comment]
@Kprellz 
cheers mate, you saved me from pulling out more hair :)
