### ISSUE TITLE
Fix for build error with adafruit nrf52 arduino (on platformio)

### ISSUE THREAD

**Issue by geeksville** [adafruit/Adafruit_TinyUSB_Arduino#82]
Hi,

I'm attaching a certainly wrong fix for a build error I just encountered building master of adafruit_nrf52  on platformio.  I'll also submit a cleaner and more usable PR to that project to properly import the new crypt lib .

This ugly 'fix' I've made is just to  fix a gcc compile error when it sees a conflicting definition for hid_gamepad_report_t.  Mentioning it here in case others have the same problem and can make a nicer change.

https://github.com/geeksville/Adafruit_TinyUSB_ArduinoCore/commit/4d0f9be85ae156fa615903ad1b728417792832a1

**Comment by hathach** [comment]
Closed since lots of changes has been done. Can be reopened or pr-ed if needed
