### ISSUE TITLE
update to get fix to MIDI sys ex

### ISSUE THREAD

**Issue by mzero** [adafruit/Adafruit_TinyUSB_Arduino#84]
Adafruit cores that incorporate this variant of the TinyUSB stack have a serious bug that renders it impossible to send MIDI SysEx messages.

The bug was fixed in TinyUSB back in september... but must get pulled in here first, then pulled into relevant cores, to create working base for users' sketches.

- The original bug report is here: https://github.com/hathach/tinyusb/issues/511
- And the pull request for the fix: https://github.com/hathach/tinyusb/pull/512
- The fix was merged into TinyUSB on Sept 22nd here: 
   https://github.com/hathach/tinyusb/commit/8b2c82255750488232eae72f3d5dcbacfd6227f3#diff-716fd87d6209145578ccbd94da446baf17157c5d7c7fd1e6ab1deae10ba5328d

I'm hoping that see the fixed TinyUSB can be merged here... so that we can eventually have cores that work for sending MIDI Sys Ex.

**Comment by hathach** [comment]
should be fixed by after release 1.0.0
