### ISSUE TITLE
remote wakeup does not work with nRF52840

### ISSUE THREAD

**Issue by ogatatsu** [adafruit/Adafruit_TinyUSB_Arduino#93]
**Set up**

- Your OS (mac/windows/linux) and Arduino IDE version
Windows 10 and Arduino 1.8.15
- Your Board and BSP version
Adafruit nRF52840 Feather Express, 0.22.1
- TinyUSB library version
1.0.3

**Describe**
remote wakeup does not work on feather nRF52840, it works on Itsy Bitsy M0. 

**To Reproduce**

1. Write a sketch of hid_mouse.ino on the board.
2. Press UserSw and make sure the pointer moves.
3. Put the PC to sleep.
4. Press UserSw.

**Comment by hathach** [comment]
ah right, I don't remember tested this before on nrf. Will check it later on.

**Comment by hathach** [comment]
@ogatatsu https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/123 fully implement suspend, resume and remote wakeup for nrf5x. Would you mind trying it out !!
